name: Tests
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      #TODO(matrix): this is here only because the strategy requires some matrix to be specified, decide how to actually utilize this better
      matrix:
        rosdistro: [ humble ]

    name: Code builds on ${{ matrix.rosdistro }}
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup environment for ROS ${{ matrix.rosdistro }}
        shell: bash
        run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash
      - name: Build ROS Package
        shell: bash
        run: colcon build

  tests:
    strategy:
      fail-fast: false
      #TODO(matrix): this is here only because the strategy requires some matrix to be specified, decide how to actually utilize this better
      matrix:
        rosdistro: [ humble ]

    name: Tests to run on ${{ matrix.rosdistro }}
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup environment for ROS ${{ matrix.rosdistro }}
        shell: bash
        run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash
      - name: Build ROS Package
        shell: bash
        run: colcon build
      - name: Run Tests
        shell: bash
        run: colcon test --ctest-args tests
      - name: Show Test Results
        shell: bash
        run: colcon test-result --verbose --all
