name: Tests
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      #TODO(matrix): this is here only because the strategy requires some matrix to be specified, decide how to actually utilize this better
      matrix:
        rosdistro: [ humble ]

    name: Code builds on ${{ matrix.rosdistro }}
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Webots
        shell: bash
        run: |
          sudo apt install wget
          sudo mkdir -p /etc/apt/keyrings
          cd /etc/apt/keyrings
          sudo wget -q https://cyberbotics.com/Cyberbotics.asc
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/Cyberbotics.asc] https://cyberbotics.com/debian binary-amd64/" | sudo tee /etc/apt/sources.list.d/Cyberbotics.list
          sudo apt update && sudo apt install webots
      - name: Build ROS Package
        shell: bash
        run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash && colcon build

  tests:
    strategy:
      fail-fast: false
      #TODO(matrix): this is here only because the strategy requires some matrix to be specified, decide how to actually utilize this better
      matrix:
        rosdistro: [ humble ]

    name: Tests to run on ${{ matrix.rosdistro }}
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Webots
        shell: bash
        run: |
          sudo apt install wget
          sudo mkdir -p /etc/apt/keyrings
          cd /etc/apt/keyrings
          sudo wget -q https://cyberbotics.com/Cyberbotics.asc
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/Cyberbotics.asc] https://cyberbotics.com/debian binary-amd64/" | sudo tee /etc/apt/sources.list.d/Cyberbotics.list
          sudo apt update && sudo apt install webots
      - name: Build ROS Package
        shell: bash
        run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash && colcon build
      - name: Run Tests
        shell: bash
        run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash && colcon test --ctest-args tests
      - name: Show Test Results
        shell: bash
        run: source /opt/ros/${{ matrix.rosdistro }}/setup.bash && colcon test-result --verbose --all
